const { Game } = require("./Game");
let game = new Game("druva", "basu");
game.play(0);
game.play(9);
game.play(0);
game.play(4);
game.play(1);
game.play(3);
game.play(2);
game.play(6);
game.play(7);
game.play(8);
game.play(5);
